### ISSUE TITLE
Exception complaining about notes not having titles

### ISSUE THREAD

**Issue by gmuller** [andymatuschak/note-link-janitor#1]
I tried this for the first time and wanted to report it 

```
(node:20305) UnhandledPromiseRejectionWarning: Error: 202002182121.md has no title
    at readNote (/Users/grantmuller/.config/yarn/global/node_modules/@andymatuschak/note-link-janitor/dist/lib/readAllNotes.js:18:15)
    at async /Users/grantmuller/.config/yarn/global/node_modules/@andymatuschak/note-link-janitor/dist/lib/readAllNotes.js:35:88
    at async Promise.all (index 3)
    at async Object.readAllNotes [as default] (/Users/grantmuller/.config/yarn/global/node_modules/@andymatuschak/note-link-janitor/dist/lib/readAllNotes.js:35:25)
    at async /Users/grantmuller/.config/yarn/global/node_modules/@andymatuschak/note-link-janitor/dist/index.js:16:19
(node:20305) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I had to guess this is a race condition in an async function, not sure though. I'll try to help out with troubleshooting sometime this week.

Environment:
MacOSX running 10.15.3
Node version 13.8.0

**Comment by frandsoh** [comment]
[Try this fork](https://github.com/houshuang/note-link-janitor)  - worked for me

**Comment by andymatuschak** [comment]
Ah, the script assumes that a note's first line is its title, formatted as a H1, i.e.

```
# Note title here

A first paragraph...
```

I'll update the Readme to explain that.
